theme: jekyll-theme-minimal

title: easySetup
description: Una única aplicación para comparar tu hardware, descubrir piezas nuevas, conocer gente con tus intereses y mantener tu equipo a punto con los últimos controladores y actualizaciones